lib/lita/adapters/slack/slack_user.rb
lib/lita/adapters/slack/user_creator.rb
spec/lita/adapters/slack/rtm_connection_spec.rb
spec/lita/adapters/slack/user_creator_spec.rb

We need to keep some Slack user information synchronized with other components of our setup. Upon such a change, Slack will send the "user_change" message, which lita-slack handles via `UserCreator.create_user`. The :slack_user_created even will also be triggered when the adapter first connects, via the `RTMConnection` and `UserCreator.create_users`.
This event allows us to handle all such updates in a pretty independent and decoupled manner.
This solution should also solve #19.

Trigger :slack_user_created event with raw data

---

lib/lita/adapters/slack/api.rb
lib/lita/adapters/slack/channel_mapping.rb
lib/lita/adapters/slack/message_handler.rb
lib/lita/adapters/slack/rtm_connection.rb
lib/lita/adapters/slack/slack_channel.rb
lib/lita/adapters/slack/team_data.rb
spec/lita/adapters/slack/api_spec.rb
spec/lita/adapters/slack/channel_mapping_spec.rb
spec/lita/adapters/slack/message_handler_spec.rb
spec/lita/adapters/slack/rtm_connection_spec.rb
spec/lita/adapters/slack/slack_channel_spec.rb

Currently url formatting breaks plugins like whois which require original un-formatted url to work.
<http://www.domain.com|www.domain.com> -> www.domain.com
<http://www.domain.com> -> http://www.domain.com
This only un-formats urls. more work would be needed to unformat every thing else that slacks chat engine changes. if slack changes its formating in the future this will break!
this should make most plugins that use urls work. 
sorry I currently have no l clue how to test this

remove url formatting on slack messages

---

lib/lita/adapters/slack/message_handler.rb
spec/lita/adapters/slack/message_handler_spec.rb

This fixes #45. 
If a user mentions @erik, Slack hands this off as &lt;@UNIQUEID&gt;, we should expand it back to @erik, not @Erik Ogan.

<@UNIQUEID> should be translated to @mention_name not @name.

---

lib/lita/adapters/slack/slack_user.rb
spec/lita/adapters/slack/rtm_connection_spec.rb
spec/lita/adapters/slack/slack_user_spec.rb
spec/lita/adapters/slack/user_creator_spec.rb

Adds the user's email address to the available attributes on a SlackUser. Slack always requires an email address, as far as I can tell, for user accounts so this should be safe to be here.  This could be a potentially breaking change since it changes the initializer for SlackUser though.
This is related to #22. 
@kenjij 
cc/ @byroot @Sirupsen

Adds email address to SlackUser object

---

lib/lita/adapters/slack/user_creator.rb
spec/lita/adapters/slack/user_creator_spec.rb

Look like we got the Slack payload wrong. The email is actually nested inside the `profile` key.
@jimmycuadra @pallan @sirupsen for review please.

Add the entire Slack profile as Lita::User metadata

---

lib/lita/adapters/slack.rb
lita-slack.gemspec
spec/lita/adapters/slack_spec.rb
spec/spec_helper.rb

A while back, Lita [added the ability](https://github.com/litaio/lita/commit/51a4b7b773a167c2a2cc9de7a09722ddb071008f#diff-a33353c254ef9eda5f85b76262531d85) to call mention_format on adapters, to better handle referencing a user on a service.  Here's a PR to add the same to this adapter.

Add mention_format method

---

lib/lita/adapters/slack/message_handler.rb

Use fallback for attachments, where text is not avaliable.

Use fallback for attachments, where text is not avaliable

---

lib/lita/adapters/slack/message_handler.rb
lita-slack.gemspec
spec/lita/adapters/slack/message_handler_spec.rb

Timestamps of an incoming message, being its only _unique identifier_ needs to be stored for referring back to the message (for eg: to associate reactions to it). This PR proposes using the newly introduced `extensions` hash of the `Message` object to store the same while dispatching.

Store timestamp of message in Message.extensions

---

README.md
lib/lita/adapters/slack.rb
lib/lita/adapters/slack/api.rb
spec/lita/adapters/slack/api_spec.rb
spec/lita/adapters/slack_spec.rb

Superseed: https://github.com/kenjij/lita-slack/pull/68
Note that enabling the full parsing mode, is not 100% backward compatible. People that were formatting their message for the real time api will have to stop, e.g. `<@U0348FF3M|byroot>` becomes just `@byroot`.
If you absolutely want to preserve 100% the backward compatibility, then we can make the parse mode configurable, and default to `none`.
@jimmycuadra @ajrkerr for review please.

Use the Web API to submit messages in full parse mode.

---

lib/lita/adapters/slack/api.rb
spec/lita/adapters/slack/api_spec.rb

So we don't have to rely on our own forks of the adapter to make sense of Slack's error messages while debugging.

Make error messages more verbose.

---

lib/lita/adapters/slack/message_handler.rb
spec/lita/adapters/slack/message_handler_spec.rb

Based on recommendations provided as feedback for https://github.com/litaio/lita-slack/pull/78 . `message_handler.rb` has been modified to include a `handle_reaction` method which triggers two new events named `:slack_reaction_added` and `:slack_reaction_removed` with a payload consistent with the slack convention for reaction objects. 
Two new test cases have also been included in `message_handler_spec.rb` to test event triggering.

Trigger slack_reaction_added/removed events

---

lib/lita/adapters/slack.rb
lib/lita/adapters/slack/api.rb
spec/lita/adapters/slack/api_spec.rb
spec/lita/adapters/slack_spec.rb

Fulfilling this request litaio/lita#69 for lita-slack. 
`robot.roster room_id` will now return user UID(s) in an Array or String for Channels, Groups, MPIMs, & IMs.

Implemented roster method for Adapter

---

README.md
lib/lita/adapters/slack.rb
lib/lita/adapters/slack/api.rb
spec/lita/adapters/slack/api_spec.rb

Instead of having a single `parse` configuration, this allows to set options to be merged in each call to `chat.postMessage` when using the Web API.
This lets us use different options than `parse: full` that we wanted to use, namely `link_names: 1` to parse `@users` and `#channels`, all the while letting URLs like `<https://www.lita.io/|Lita>` be parsed by Slack.
cc @byroot

config.postMessage instead of config.parse

---

lib/lita/adapters/slack/message_handler.rb
spec/lita/adapters/slack/message_handler_spec.rb

We were having a lot of `cannot_dm_bot` errors in production. After some investigation it occured that our Lita bot was seeing it's own responses when you were talking to it via direct messages.
I don't know if the Slack API changed and the `subtype` isn't sent anymore, of it the doc is lying and it was never sent. However it's clearly missing today.
Here's what the payload look like for a bot seeing itself talking:
```ruby
{"type"=>"message", "user"=>"U0MK1JVGX", "text"=>":pong:", "bot_id"=>"B0MK2975E", "user_team"=>"T024G4BGQ", "team"=>"T024G4BGQ", "channel"=>"D0MK2RZGA", "ts"=>"1461946141.000024"}
```
Also the current code use `User.find_by_name(robot.name)`, so the config absolutely need to be accurate otherwise Lita can't identify itself.
The new code is way more robust in my …

Fix and simplify MessageHandler#from_self

---

lib/lita/adapters/slack/message_handler.rb

See https://github.com/litaio/lita-slack/issues/94

Remove bot_message from supported_message_subtypes

---

lib/lita/adapters/slack.rb

This threw me for a loop as a few of our handlers started blowing up as new slack channels are starting with `C1...`  I cannot find any specification that list the 0 as a required number, only that 100% of the examples have a zero.
This removes the trailing zero to support new channels, ids and groups.

Slack API does not specify that the second character be zero.

---

lib/lita/adapters/slack/message_handler.rb
spec/lita/adapters/slack/message_handler_spec.rb

The other day, our lita bot responded to a message that came from [slackbot](https://get.slack.help/hc/en-us/articles/202026038-Slackbot-personal-assistant-and-helpful-bot-), the bot that comes built into slack. This seems bad.
https://github.com/litaio/lita-slack/pull/95 didn't help because messages only have subtype [`bot_message`](https://api.slack.com/events/message/bot_message) if they come from _integration_ bots, which slackbot is not. It seems that the only thing that distinguishes a slackbot message from other messages is the originating user. Slackbot's userid is `USLACKBOT`.
This change aborts handling a message that comes from the slackbot user.
It's not documented anywhere, but I have confirmed with the slack team that the way you check if a message is from slackbot is by …

Ignore messages from slackbot

---

README.md
lib/lita/adapters/slack/message_handler.rb
spec/lita/adapters/slack/message_handler_spec.rb

Both `slack_reaction_added` and `slack_reaction_remove` events include the user that
created the original item that has been reacted to.
More information:
https://api.slack.com/events/reaction_added
https://api.slack.com/events/reaction_removed

Add "item_user" to payload of reaction events

---

lib/lita/adapters/slack/message_handler.rb
spec/lita/adapters/slack/message_handler_spec.rb

@jimmycuadra This should fix #44.
Before, the channel ID was being set as both the `id` and `name` within the message's `room_object`.
This PR will either lookup the correct room object, which would have a name, or it will assign the channel ID as a fallback (which will happen when it's a private conversation without a name). This relies on [`Lita::Source` accepting either a `Lita::Room` or a `String`](https://github.com/litaio/lita/blob/63c0aea704202ae1e7d5021ec14ad51e8bb1735a/lib/lita/source.rb#L43-L49).

Properly set the room name in received messages

---

.gitignore
lib/lita/adapters/slack/event_loop.rb
lib/lita/adapters/slack/rtm_connection.rb
spec/lita/adapters/slack/rtm_connection_spec.rb

Couple of fixes to different issues in shut down logic that all lead to such errors in different scenarios:  
`RuntimeError: eventmachine not initialized: evma_install_oneshot_timer`
1) There's a problem with shutting down strategy introduced in this commit:
https://github.com/litaio/lita-slack/commit/b27046fb13bbe59fc31ad27d0fdf16b63077f712
the `shut_down` method that has been added to `:close` callback on websocket, tries to close websocket itself, triggering shutdown logic twice and attempting to turn off the EM twice as well, with the second attempt failing. To make it happen only once, I've substituted it with direct EM shutting down command.
2) Websocket ensures to be closed itself, when EM, where it operates on, is shut down: …

Several bugfixes for improper closing of websocket and eventmachine
